### ISSUE TITLE
Favicon doesn't show up right 

### ISSUE THREAD

**Issue by sihrc** [boolio/boolio-landingWeb#8]
![screen shot 2015-06-28 at 4 56 30 pm](https://cloud.githubusercontent.com/assets/3360831/8398300/a5af0586-1db6-11e5-93a0-b1f8c4e083cb.png)

**Comment by flymperopoulos** [comment]
do you mean the bear @sihrc ?

**Comment by jenwei** [comment]
![image](https://cloud.githubusercontent.com/assets/6274515/8399360/94a0d412-1dc1-11e5-9c25-5506061a489e.png)

The bear isn't in 'icon'.

Did you want the favicon to look like this?
![image](https://cloud.githubusercontent.com/assets/6274515/8399379/32538268-1dc2-11e5-9a90-e3129b95cb07.png)

**Comment by flymperopoulos** [comment]
on purpose I left it without the bear, because I liked the simplicity in the header of the tab.

**Comment by sihrc** [comment]
oh ! haha, okay.
